![imagen](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRv7-9e8oYLYuPJ2mPM3YOlHoKFiHaQCFClWRKVBOzUe1CWABtg5QtluntYIxiHgpYNdw&usqp=CAU)

# Computación Científica

# Algebra en Python: Numpy

In [31]:
import numpy as np
numeros = np.arange(1,13)

## Arrays especiales

Muchas veces necesitaremos crear matrices rápidamente, sin cargar uno por uno sus elementos, NumPy nos provee con varias alternativas para hacerlo.

### Vector formada por unos

In [3]:
# Escriba aquí su código
Vector = np.ones(5)
Vector

array([1., 1., 1., 1., 1.])

### Matriz formada por unos

In [4]:
# Escriba aquí su código
Matriz = np.ones((4,4))
Matriz

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Cree una matriz de 4 filas y 6 columnas formada por unos.

In [6]:
# Escriba aquí su código
Matriz2 = np.ones((4,6))
Matriz2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

Obviamente si necesitara una matriz formada toda por cincos, bastaría con multiplicar la matriz anterior por 5

In [7]:
# Escriba aquí su código
Matriz2 *= 5
Matriz2

array([[5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5.]])

También es posible crear esta matriz usando:

### Vector formado por todos sus elementos iguales

In [3]:
# Escriba aquí su código
np.full(10,10)
#np.full (cantidad de elementos, tipo de elemento) 

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [7]:
np.full(2,5)

array([5, 5])

### Matriz formada por todos sus elementos iguales

In [8]:
# Escriba aquí su código
np.full((5,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [ ]:
#Esta matriz tiene 4 dimensiones como podse ver si seguis los [] vas a ver como te determina las dimensiones y aunque
#visualmente es complicado de leer puede hacerse y creo que de esto se va a tratar trabajar en ciencia de datos. no le pongas run
np.full((3,5,4,3),6)

### Vector Nulo: formado por ceros

In [13]:
# Escriba aquí su código
np.zeros(4)

array([0., 0., 0., 0.])

### Matriz Nula:  formada por ceros

In [14]:
# Escriba aquí su código
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Matriz Identidad

Las matrices identidad son aquellas **matrices cuadradas** cuya **diagonal principal está formada por unos y el resto de sus elementos son todos ceros**.  

Por ejemplo la siguente es la matriz Identidad de orden 3 
$$I_3=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$  

Para crear se utiliza la función np.eye(orden), dado que es una matriz cuadrada en orden sólo se indica un número.  
Por ejemplo para crear la matriz anterior:


In [21]:
# Escriba aquí su código
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Cree una matriz cuadrada de orden 5, cuya diagonal principal está formada por cuatros. 

In [20]:
# Escriba aquí su código
4 * np.eye(5)


array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

### Matriz de números aleatorios

Numpy provee de diversas funciones para obtener números aleatorios. 

Por ejemplo:  

*np.random.random([size])*  

devuelve una cantidad = size de números al azar entre [0,1[  (Nota: incluye al 0 pero **no** inlcuye al 1)


Obtenga una secuencia de 5 números aleatorios entre [0,1[ 

In [30]:
# Escriba aquí su código
np.random.random(5)

array([0.29549878, 0.11506059, 0.8922121 , 0.9806878 , 0.35568716])

Observe que si ejecuta el código anterior los valores obtenidos serán distintos cada vez que ejecute.  
Si necesita que los números aleartorios generados sean siempre los mismos, por ejemplo para conseguir "repetibilidad" de un experimento, deberá primero crear una semilla (seed).  

Nota: En el caso de Jupyter el  valor de la seed se mantiene sólo dentro de la misma celda. Por las dudas, verifique.  


Por ejemplo, ejecute varias veces el siguiente código y observe si los números aleatorios generados son siempre los mismos. 

In [42]:
# Asigno el punto de partida, la semilla
np.random.seed([123])
np.random.random(4)

array([0.0523636 , 0.08718668, 0.40724176, 0.10770023])

A veces necesitamos generar números decimales (float) aleatorios en otro rango que no sea [0,1[  , en ese caso podemos usar random.uniform()  :

~~~
np.random.uniform(low=0.4, high=24.7, size=(10,))
~~~

In [47]:
# Escriba aquí su código
np.random.uniform(low=0.5, high=0.6, size=(10,))

array([0.54362758, 0.50876135, 0.55975995, 0.5069877 , 0.5315459 ,
       0.54483217, 0.59053987, 0.50927646, 0.51421751, 0.57900718])

In [54]:
np.random.seed([31])
np.random.uniform(low=1.0, high=1.1, size=(2,2))

array([[1.00122782, 1.01123989],
       [1.03928374, 1.06838643]])

Si necesitamos que sean números enteros: 

**randint(low[, high, size, dtype])**    

(nota: incluye a low, pero **no** incluye a high)

Por ejemplo si necesitamos 4 números enteros entre 1 y 10 (inclusive ambos)




In [8]:
# Escriba aquí su código
#np.random.randint(Mayor igual,menor que,Tamaño de vector o matriz)
np.random.randint(1,10,20)

array([8, 4, 6, 1, 8, 5, 3, 8, 1, 7, 2, 4, 9, 4, 4, 4, 1, 3, 8, 9])

### Matriz de números aleatorios decimales

In [60]:
# Escriba aquí su código
np.random.randint(10,100,(8,8))

array([[58, 75, 94, 92, 13, 21, 67, 91],
       [20, 91, 50, 99, 69, 75, 50, 85],
       [91, 48, 42, 30, 83, 31, 71, 91],
       [16, 10, 59, 27, 36, 82, 63, 35],
       [46, 10, 57, 57, 62, 30, 37, 27],
       [68, 39, 61, 51, 13, 51, 11, 39],
       [72, 68, 48, 96, 12, 73, 84, 57],
       [67, 76, 52, 52, 25, 96, 41, 63]])

Nuevamente, si necesitamos que los valores generados al azar sean los mismos cada vez que se ejecute la celda:

In [63]:
# Escriba aquí su código
np.random.seed([605])
np.random.randint(1,10,8)

array([7, 5, 2, 7, 5, 6, 8, 3])

### Matriz de números aleatorios enteros

In [15]:
# Escriba aquí su código

## Creación de secuencias útiles

### numpy.arange
Supongamos que por algún motivo necesitamos crear una secuencia de números impares hasta el 100, hacerlo manualmente puede ser muy incómodo, pero tenemos la función arange.  
Su sintaxis es la siguiente:  


numpy.arange([start, ]stop, [step, ]dtype=None

(Consulte el Manual onlin de NumPy en: https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html )

- NumPy tomará como rango **desde el valor start inclusive** y se extenderá **hasta el valor step sin tomarlo**, es decir en el intervalo [start,stop[.  
- Por defecto inicia la secuencia en  0 con un step de 1 y determina el tipo de dato según los utilizados en la función


In [14]:
# Escriba aquí su código
np.arange(0,7,2)

array([0, 2, 4, 6])

Ahora podemos crear nuestra secuencia de números impares desde el 1 hasta el 100. (1,3,5 ....99)

In [69]:
# Escriba aquí su código
np.arange(0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Ejercicio:  
Cree una secuencia de números desde el 1 hasta al 100 inclusive múltiplos de 10. (10, 20, 30, ..., 100)

In [71]:
# Escriba aquí su código
np.arange(0,101,10)


array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Cree la secuencia 1 ,1.2 ,1.4,1.6 ...5

In [73]:
# Escriba aquí su código
np.arange(1,5.1,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. ])

In [4]:
#También es posible crear secuencias descendentes, no olvide poner el salto o step con un valor negativo.
#Cree el vector (10,9,8,..,1)
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [81]:
# Escriba aquí su código
np.arange(100,-100,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,
        -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13, -14, -15, -16,
       -17, -18, -19, -20, -21, -22, -23, -24, -25, -26, -27, -28, -29,
       -30, -31, -32, -33, -34, -35, -36, -37, -38, -39, -40, -41, -42,
       -43, -44, -45, -46, -47, -48, -49, -50, -51, -52, -53, -54, -55,
       -56, -57, -58, -59, -60, -61, -62, -63, -64, -65, -66, -67, -68,
       -69, -70, -71, -72, -73, -74, -75, -76, -77, -78, -79, -8

## Convertir a array

### numpy.reshape

Muchas veces nos interesará poblar una matriz con números de alguna secuencia; en NumPy podemos transformar arrays con distinta cantidad de ejes entre sí. 

numpy.reshape(a, newshape, order='C')  
(consulte el Manual online de Numpy en: https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

a: es el array original  
newshape: es la cantidad de valores en cada eje que deseamos que tenga el resultado 



Supongamos que creamos un array con los 9 números enteros del 1 al 9.

In [102]:
numeros= np.arange(1,10,1)
numeros

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

y ahora queremos disponerlos en forma de matriz de 3 filas y 3 columnas, un una matriz es decir un array de 2 ejes:

In [103]:
# Escriba aquí su código
np.reshape(numeros,(3,3))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Por supuesto que no era necesario crear primero el array numeros, podríamos haber hecho:

In [104]:
# Escriba aquí su código
print(np.reshape(np.arange(1,10),(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ejercicio:  
Cree la siguiente matriz:
$$\begin{bmatrix} 1 & 1.5 & 2 & 2.5\\ 3 & 3.5 & 4 & 4.5\\ 5 & 5.5 & 6 & 6.5 \end{bmatrix}$$ 

In [106]:
#Escriba aquí su código
np.arange(1,7,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

También es posible cambiar una matriz en otra, con los mismos números pero distinta cantidad de filas y columnas:

In [107]:
np.reshape(np.arange(1,13),(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
# Escriba aquí su código
np.reshape(np.arange(1,26),(5,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Convierta matriz_01 en una matriz con 6 filas y 2 columnas:

In [110]:
# Escriba aquí su código
np.reshape(np.arange(1,13),(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Ahora conviértala en una matriz que tenga 2 filas y 6 columnas

In [111]:
# Escriba aquí su código
np.reshape(np.arange(1,13),(2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

**El uso de -1 en reshape**  

En algunas circunstancias el -1 puede funcionar como un comodín, observe el siguiente código:

In [113]:
# Escriba aquí su código
np.reshape(np.arange(1,13),(6,-1))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Observe el siguiente código:

In [15]:
# Escriba aquí su código
np.reshape(np.arange(1,31),(3,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

Explique aquí, qué papel jugó el -1 en los dos casos anteriores: 
    


### Flatten

Flatten sirve para transformar un array de varios ejes en uno de un solo eje, su sintaxis es como la siguiente:  

**matriz.flatten()**


In [25]:
# Escriba aquí su código
import numpy as np
matriz_01=np.reshape(np.arange(1,13,1),(3,4))
matriz_01
matriz_02=np.reshape(matriz_01,(4,3))
matriz_02
matriz_01.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Cómo hubiera transformado a matriz_01 en un vector pero usando reshape?

In [22]:
# Escriba aquí su código
np.reshape(matriz_01,(1,12))
#tambien funciona si pones el -1
np.reshape(matriz_01,(1,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [29]:
matriz_02

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
matriz_02.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Transpuesta de una matriz

Para transponer una matriz, simplemente:  
    
matriz.T    

Recordemos cómo era la matriz_01 y luego hallemos su transpuesta:

In [23]:
# Escriba aquí su código
matriz_01

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# Escriba aquí su código
matriz_01.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## Arrays Booleanos

A veces será necesario crear arrays con valores True o False, esto también es posible en NumPy

In [36]:
# Escriba aquí su código
np.array([[True,False],[True ,False]])

array([[ True, False],
       [ True, False]])

También podríamos crear una matriz 3x3 con todos False

In [37]:
# Escriba aquí su código
np.full((3,3),False)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

Cree una matriz 2x4 con valores True

In [38]:
# Escriba aquí su código
np.full((2,4),True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Los arrays con valores booleanos suelen aparecer como resultados de ciertas operaciones, por ejemplo cuando comparamos valores:


Se acuerda cómo era el vector numeros?

In [41]:
# Escriba aquí su código
numeros

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
# Escriba aquí su código
# < > <= >= != ==
numeros >= 3

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [ ]:
#distinto
numeros != 3

Observe que devolvió un array con True en las posiciones en las cuales se cumplió la condición y con  False en aquellas donde no se cumplió la condición.

En qué ubicaciones se encuentran los valores mayores a 4?

In [52]:
# Escriba aquí su código
numeros >= 4

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

y para los mayores o iguales a 4?

In [10]:
# Escriba aquí su código
numeros <= 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False])

In [11]:
#Cuantos son true?
sum(numeros <= 4)

4

## Truco

Cuántos elementos mayores o iguales a 4 hay en el vector numeros?

In [12]:
# Escriba aquí su código
sum(numeros>=4)

9

Ocurre que internamente maneja a los True como unos y a los False como 0, por eso funciona.

Cree una matriz de 10x4 con números aleatorios entre 1 y 100 inclusive generados con la semilla (seed=321). Llámela matriz 

In [37]:
# Escriba aqui su código
# Cree una matriz de 10x4 con numeros aleatorios del 1 al 100 generados con la semilla 321
np.random.seed([321])
Matriz = np.random.randint(1,101,(10,4))
Matriz

Cuente cuántos de sus elementos son mayores o iguales que 20

In [18]:
# Escriba aqui su código
#aca te suma los elementos mayores a 20 de cada fila y los deja en una sola.
sum(Matriz>=20)

array([9, 8, 7, 9])

In [17]:
# Escriba aqui su código
sum(sum(Matriz>=20))

33

## Archivo NPY

Los archivos NPY se utilizan en NumPy para almacenar la información de los archivos de matrices necesaria para llevar a cabo el análisis de datos requerido. Los archivos NPY almacenan los datos de la matriz en un formato de archivo binario.

El archivo de matrices NPY puede cargarse utilizando la función np.load('nombrefichero.npy'), donde nombrefichero.npy es el archivo NPY que ya contiene la matriz. La función numpy.load() toma el nombre del archivo como parámetro de entrada y devuelve la matriz. 

Si se cuenta con un archivo de este tipo se levanta la información en una matriz mediante la siguiente instrucción.

**np.load('ruta/nombre.extensión')**

Ej:

**np.load('datos/ratings_movie_lens.npy')**

La función numpy.save() se utiliza para grabar datos de una matriz a un archivo.

La función toma el nombre del archivo y la matriz a guardar como parámetros de entrada y guarda la matriz dentro del archivo especificado. 

El siguiente ejemplo de código nos muestra cómo podemos guardar y cargar una matriz NumPy con las funciones numpy.save() y numpy.load() en Python.

**import numpy as np**

**a = np.array([1, 3, 5, 7])**

**np.save('test3.npy', a)**

**a2 = np.load('test3.npy')**


In [39]:
# Escriba aquí el código que grabe el array
import numpy as np

a = np.array([1, 3, 5, 7])

np.save('Datos/prueba.npy', a)

In [40]:
# Escriba aquí el código que muestre el array grabado
a2 = np.load('Datos/prueba.npy')
a2

array([1, 3, 5, 7])

## Ejemplo

Cargue el array de datos ratings_movie_lens.npy en un array denominado calificaciones

In [41]:
# Escriba aquí el código que cargue la matriz
calificaciones = np.load('Datos/ratings_movie_lens.npy')
calificaciones

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [38]:
# Escriba aquí el código que muestre el tamaño de la matriz
calificaciones.size

1586126

In [42]:
# Escriba aquí el código que muestre la matriz
np.linalg.norm(calificaciones)

1171.6245132293877